[build-system]
requires = ["setuptools>=45", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "linux-plus-study-v2"
version = "2.0.0"
description = "Enhanced Linux Plus certification study tool"
